import { StyleSheet } from "react-native";
import { COLORS } from "./constants";

export const styles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: COLORS.cream },
  loading: {
    flex: 1,
    backgroundColor: COLORS.cream,
    alignItems: "center",
    justifyContent: "center",
  },
  authContainer: {
    flexGrow: 1,
    justifyContent: "center",
    padding: 28,
    backgroundColor: COLORS.cream,
  },
  logoRow: { flexDirection: "row", alignItems: "center", gap: 9 },
  logoTile: {
    width: 34,
    height: 34,
    backgroundColor: COLORS.ink,
    alignItems: "center",
    justifyContent: "center",
    transform: [{ rotate: "-5deg" }],
  },
  logoTileText: { color: COLORS.lime, fontSize: 21, fontWeight: "900" },
  logoText: {
    color: COLORS.ink,
    fontSize: 24,
    fontWeight: "800",
    letterSpacing: -1,
  },
  authIntro: { marginTop: 66, marginBottom: 36 },
  eyebrow: {
    color: COLORS.muted,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.4,
  },
  authTitle: {
    color: COLORS.ink,
    fontSize: 42,
    lineHeight: 44,
    fontWeight: "800",
    letterSpacing: -1.2,
    marginTop: 12,
  },
  authSubtitle: {
    color: COLORS.muted,
    fontSize: 16,
    lineHeight: 23,
    marginTop: 16,
    maxWidth: 320,
  },
  form: { gap: 10 },
  inputLabel: {
    color: COLORS.ink,
    fontSize: 13,
    fontWeight: "800",
    marginTop: 10,
  },
  input: {
    height: 54,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: "#FCFBF7",
    paddingHorizontal: 16,
    fontSize: 16,
    color: COLORS.ink,
  },
  error: { color: "#C84F3E", fontSize: 13, marginTop: 4 },
  primaryButton: {
    height: 56,
    backgroundColor: COLORS.lime,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 18,
  },
  primaryButtonText: { color: COLORS.ink, fontSize: 15, fontWeight: "900" },
  disabledButton: { opacity: 0.45 },
  switchButton: { alignItems: "center", padding: 13 },
  switchText: { color: COLORS.ink, fontSize: 14, fontWeight: "700" },
  privacyNote: {
    color: COLORS.muted,
    fontSize: 12,
    lineHeight: 17,
    textAlign: "center",
    marginTop: 42,
    paddingHorizontal: 18,
  },
  homeContainer: { padding: 24, paddingBottom: 36 },
  nav: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  signOut: { color: COLORS.muted, fontSize: 13, fontWeight: "700" },
  greeting: { marginTop: 58 },
  homeTitle: {
    color: COLORS.ink,
    fontSize: 33,
    lineHeight: 37,
    fontWeight: "800",
    letterSpacing: -0.8,
    marginTop: 10,
  },
  homeSubtitle: { color: COLORS.muted, fontSize: 16, marginTop: 8 },
  streakRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.ink,
    marginTop: 30,
    padding: 19,
  },
  streakNumber: { color: COLORS.lime, fontSize: 27, fontWeight: "900" },
  streakLabel: {
    color: "#B8C0B9",
    fontSize: 11,
    fontWeight: "700",
    marginTop: 2,
  },
  streakDivider: {
    width: 1,
    height: 37,
    backgroundColor: "#44504A",
    marginHorizontal: 28,
  },
  streakFlame: { color: COLORS.coral, fontSize: 32, marginLeft: "auto" },
  sectionTitle: {
    color: COLORS.ink,
    fontSize: 20,
    fontWeight: "800",
    marginTop: 38,
    marginBottom: 15,
  },
  gameCard: { padding: 20, marginBottom: 13, minHeight: 174 },
  lockedCard: { opacity: 0.58 },
  cardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardIcon: { color: COLORS.ink, fontSize: 25, fontWeight: "900" },
  cardStatus: {
    color: COLORS.ink,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.5,
  },
  cardTitle: {
    color: COLORS.ink,
    fontSize: 25,
    fontWeight: "900",
    marginTop: 22,
  },
  cardDescription: { color: COLORS.ink, fontSize: 14, marginTop: 5 },
  cardArrow: {
    color: COLORS.ink,
    fontSize: 13,
    fontWeight: "800",
    marginTop: 19,
  },
  footerQuote: {
    color: COLORS.muted,
    fontSize: 13,
    lineHeight: 19,
    fontStyle: "italic",
    marginTop: 28,
    maxWidth: 290,
  },
  gameContainer: { padding: 24, paddingBottom: 40 },
  gameNav: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  backText: { color: COLORS.ink, fontSize: 14, fontWeight: "800" },
  gameCounter: { color: COLORS.muted, fontSize: 12, fontWeight: "800" },
  gameHeading: { marginTop: 72 },
  gameTitle: {
    color: COLORS.ink,
    fontSize: 42,
    fontWeight: "900",
    letterSpacing: -1.2,
    marginTop: 12,
  },
  gameSubtitle: { color: COLORS.muted, fontSize: 16, marginTop: 7 },
  clueBox: {
    backgroundColor: COLORS.lime,
    padding: 23,
    marginTop: 35,
    marginBottom: 28,
  },
  clueLabel: {
    color: COLORS.ink,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.5,
  },
  clueText: {
    color: COLORS.ink,
    fontSize: 23,
    lineHeight: 29,
    fontWeight: "800",
    marginTop: 16,
  },
  answerInput: {
    height: 64,
    borderWidth: 2,
    borderColor: COLORS.ink,
    paddingHorizontal: 16,
    color: COLORS.ink,
    fontSize: 27,
    fontWeight: "900",
    letterSpacing: 8,
    marginTop: 3,
  },
  resultBox: { padding: 18, marginTop: 18 },
  correctBox: { backgroundColor: COLORS.lime },
  tryAgainBox: { backgroundColor: COLORS.coral },
  resultTitle: { color: COLORS.ink, fontSize: 19, fontWeight: "900" },
  resultText: { color: COLORS.ink, fontSize: 14, lineHeight: 20, marginTop: 5 },
  gameHint: {
    color: COLORS.muted,
    fontSize: 13,
    textAlign: "center",
    marginTop: 18,
  },
});
